application: jwilde-debrief
version: 6
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /html
  static_dir: html

- url: /images
  static_dir: client/images

- url: /js
  static_dir: client/js

- url: /dist
  static_dir: client/dist

- url: /css
  static_dir: client/css

- url: /.*
  script: server.apprtc.app
  secure: always

inbound_services:
- channel_presence

libraries:
- name: jinja2
  version: latest