application: rehash-tv
version: 6
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: server.apprtc.app
  secure: always

skip_files:
- ^client
- ^.git
- .DS_Store
- ^google_appengine

inbound_services:
- channel_presence

libraries:
- name: jinja2
  version: latest
- name: ssl
  version: latest